#!/bin/bash

# Private tmp vars
__ACCESS_TOKEN="${ACCESS_TOKEN}"
__MINI_PROG='lark://mini-program/open?mode=sidebar-semi&appId='

# Public vars
ROOT=$(dirname $(dirname $(realpath ${BASH_SOURCE[0]})))
WORK='/tmp'
EMAIL_SUFFIX='dosk.win'
function INCLUDE {
  source ${ROOT}/$1
}

# Include base utils
INCLUDE lib/libutils

function tenant_access_token {
  force=$1
  expire=0
  if [ "${__ACCESS_TOKEN}" == "" ] || [ "${force}" != "" ];
  then
    if [ "${ACCESS_TOKEN_STORE}" != "" ] && [ -e "${ACCESS_TOKEN_STORE}" ];
    then
      source ${ACCESS_TOKEN_STORE}
      __ACCESS_TOKEN="${ACCESS_TOKEN}"
    else
      url='/auth/v3/tenant_access_token/internal/'
      data='{"app_id":"'${APPID}'","app_secret":"'${APPSECRET}'"}'
      json=$(curl \
        'https://open.feishu.cn/open-apis'${url} \
        -X POST \
        -H 'Content-Type: application/json' \
        --data-binary "${data}" \
        --compressed 2>/dev/null)
      __ACCESS_TOKEN=$(json_parse '"tenant_access_token"' <<< "${json}" | remove_unused)
      expire=$(json_parse '"expire"' <<< "${json}")
    fi
  fi
  echo ${__ACCESS_TOKEN}
  return ${expire}
}

function base_http {
  method=$1
  url=$2
  data=$3
  access_token=$(tenant_access_token)
  curl \
    'https://open.feishu.cn/open-apis'${url} \
    -X ${method} \
    -H 'Content-Type: application/json' \
    -H 'Authorization: Bearer '${access_token} \
    --data-binary "${data}" \
    --compressed 2>/dev/null
}

function group_chat_info_list {
  query=$1
  base_http 'GET' '/chat/v4/list' '' |\
    json_parse '"data","groups",[0-9]*,"'${query}'"' |\
    xargs -n1
}

function bot_info {
  base_http 'GET' '/bot/v3/info/' ''
}

function user_id {
  email=$1
  base_http 'POST' '/user/v3/email2id' $(json_build email ${email}) |\
    json_parse '"open_id"' |\
    remove_unused
}

function user_info {
  user_id=$1
  base_http 'GET' '/user/v3/info?open_id='${user_id} ''
}

function send_message {
  id_type=$1
  id=$2
  msg_type=$3
  content=$4
  data=$(json_build ${id_type} ${id} msg_type ${msg_type} content ~"${content}")
  base_http 'POST' '/message/v3/send/' "${data}"
}

function send_card_message {
  id_type=$1
  id=$2
  title=$3
  content=$4
  button_title=$5
  button_link=$6
  data=$(
    json_build card ~$(
      json_build \
        header ~$(json_build title "${title}") \
        content ~[[$(json_build tag text text "${content}")]] \
        actions ~[$(json_build buttons ~[$(json_build text "${button_title}" method jump url "${button_link}")])]
    )
  )
  send_message ${id_type} ${id} 'interactive' "${data}" |\
    json_parse '"code"'
}

function send_text_message {
  id_type=$1
  id=$2
  content=$3
  data=$(json_build text "${content}")
  send_message ${id_type} ${id} 'text' "${data}" |\
    json_parse '"code"'
}

function reply_text_message {
  id_type=$1
  id=$2
  parent_id=$3
  content=$4
  data=$(json_build ${id_type} ${id} msg_type text root_id ${parent_id} content ~$(json_build text "${content}"))
  base_http 'POST' '/message/v3/send/' "${data}"
}

# Init process
prepare_base_util
