#!/bin/bash

# Private tmp vars
__ACCESS_TOKEN="${ACCESS_TOKEN}"
__MINI_PROG='https://applink.feishu.cn/client/mini_program/open?mode=sidebar-semi&appId='

# Public vars
ROOT=$(dirname $(dirname $(realpath ${BASH_SOURCE[0]})))
WORK='/tmp'
EMAIL_SUFFIX='dosk.win'
function INCLUDE {
  source ${ROOT}/$1
}

# Include base utils
INCLUDE lib/libutils

function tenant_access_token {
  force=$1
  expire=0
  if [ "${__ACCESS_TOKEN}" == "" ] || [ "${force}" != "" ];
  then
    if [ "${ACCESS_TOKEN_STORE}" != "" ] && [ -e "${ACCESS_TOKEN_STORE}" ];
    then
      source ${ACCESS_TOKEN_STORE}
      __ACCESS_TOKEN="${ACCESS_TOKEN}"
    else
      url='/auth/v3/tenant_access_token/internal/'
      data='{"app_id":"'${APPID}'","app_secret":"'${APPSECRET}'"}'
      json=$(curl \
        'https://open.feishu.cn/open-apis'${url} \
        -X POST \
        -H 'Content-Type: application/json' \
        --data-binary "${data}" \
        --compressed 2>/dev/null)
      __ACCESS_TOKEN=$(json_parse '"tenant_access_token"' <<< "${json}" | remove_unused)
      expire=$(json_parse '"expire"' <<< "${json}")
    fi
  fi
  echo "${__ACCESS_TOKEN}"
  return ${expire}
}

function base_http {
  method=$1
  url=$2
  data=$3
  access_token=$(tenant_access_token)
  curl \
    'https://open.feishu.cn/open-apis'${url} \
    -X ${method} \
    -H 'Content-Type: application/json' \
    -H 'Authorization: Bearer '${access_token} \
    --data-binary "${data}" \
    --compressed 2>/dev/null
}

function group_chat_info_list {
  query=$1
  base_http 'GET' '/chat/v4/list' '' |\
    json_parse '"data","groups",[0-9]*,"'${query}'"' |\
    xargs -n1
}

function bot_info {
  base_http 'GET' '/bot/v3/info/' ''
}

function user_id {
  email=$1
  base_http 'POST' '/user/v3/email2id' $(json_build email ${email}) |\
    json_parse '"open_id"' |\
    remove_unused
}

function exchange_id {
  api=$1
  id_type=$2
  id=$3
  base_http 'POST' "/exchange/v3/${api}/" "$(json_build "${id_type}" "${id}")"
}

function user_info {
  user_id=$1
  base_http 'GET' '/user/v3/info?open_id='${user_id} ''
}

function upload_image {
  file=$1
  access_token=$(tenant_access_token)
  curl \
    'https://open.feishu.cn/open-apis/image/v4/upload/' \
    -X 'POST' \
    -H 'Content-Type: multipart/form-data' \
    -H 'Authorization: Bearer '${access_token} \
    -F "image=@${file}" \
    --compressed 2>/dev/null |\
    json_parse '"data","image_key"' |\
    remove_unused
}

function send_message {
  id_type=$1
  id=$2
  msg_type=$3
  content=$4
  data=$(json_build ${id_type} ${id} msg_type ${msg_type} content ~"${content}")
  base_http 'POST' '/message/v3/send/' "${data}"
}

function send_card_message {
  id_type=$1
  id=$2
  title=$3
  content=$4
  button_title=$5
  button_link=$6
  header="$(json_build title "${title}")"
  content="[[$(json_build tag text text "${content}")]]"
  actions="[$(json_build buttons ~[$(json_build text "${button_title}" method jump url "${button_link}")])]"
  data=$(
    json_build card ~"$(
      json_build \
        header ~"${header}" \
        content ~"${content}" \
        actions ~"${actions}"
    )"
  )
  send_message ${id_type} ${id} 'interactive' "${data}" |\
    json_parse '"code"'
}

function send_text_message {
  id_type=$1
  id=$2
  content=$3
  data=$(json_build text "${content}")
  send_message ${id_type} ${id} 'text' "${data}" |\
    json_parse '"code"'
}

function reply_text_message {
  id_type=$1
  id=$2
  parent_id=$3
  content=$4
  data=$(json_build ${id_type} ${id} msg_type text root_id ${parent_id} content ~"$(json_build text "${content}")")
  base_http 'POST' '/message/v3/send/' "${data}" |\
    json_parse '"code"'
}

function send_image_message {
  id_type=$1
  id=$2
  image_key=$3
  if [ "$(is_tt_uuid ${image_key})" != "true" ];
  then
    image_key_parts=($(echo "${image_key}" | awk -F '_' '{print $1, $2}'))
    if [ "${image_key_parts[0]}" != "img" ] || [ "$(is_tt_uuid ${image_key_parts[1]})" != "true" ];
    then
      tmp_img_file=$(make_cached_file "${image_key}")
      image_key=$(upload_image "${tmp_img_file}")
    fi
  fi
  data=$(json_build image_key "${image_key}")
  send_message ${id_type} ${id} 'image' "${data}" |\
    json_parse '"code"'
}

function reply_image_message {
  id_type=$1
  id=$2
  parent_id=$3
  img_url=$4
  tmp_img_file=$(make_cached_file "${img_url}")
  image_key=$(upload_image "${tmp_img_file}")
  data=$(json_build ${id_type} ${id} msg_type image root_id ${parent_id} content ~"$(json_build image_key "${image_key}")")
  base_http 'POST' '/message/v3/send/' "${data}" |\
    json_parse '"code"'
}

# Init process
prepare_base_util
